### ISSUE TITLE
Chat Copilot - Critical failure on initiation

### ISSUE THREAD

**Issue by mavilleg** [MicrosoftDocs/semantic-kernel-docs#90]
Hello - since I change my Mac (for one running on a M3 silicon chips) I have some trouble to run the chat copilot. When initiating locally the webAPI I'm facing a critical failure - 

--------
```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.InvalidOperationException: Unable to resolve service for type 'System.Collections.Generic.IReadOnlyList`1[CopilotChat.WebApi.Services.IMaintenanceAction]' while attempting to activate 'CopilotChat.WebApi.Services.MaintenanceMiddleware'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: Unable to resolve service for type 'System.Collections.Generic.IReadOnlyList`1[CopilotChat.WebApi.Services.IMaintenanceAction]' while attempting to activate 'CopilotChat.WebApi.Services.MaintenanceMiddleware'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'System.Collections.Generic.IReadOnlyList`1[CopilotChat.WebApi.Services.IMaintenanceAction]' while attempting to activate 'CopilotChat.WebApi.Services.MaintenanceMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at CopilotChat.WebApi.Program.Main(String[] args) in /Users/mavilleg/Documents/chat-copilot/webapi/Program.cs:line 135
   at CopilotChat.WebApi.Program.<Main>(String[] args)
*************************************************
Backend is not running and we have exceeded 
the maximum number of retries.

Therefore, we are exiting.
*************************************************
```

**Comment by moonbox3** [comment]
Thanks for reaching out! The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo [link to main repo]? That way, it will get the attention it needs.

Thanks for understanding!
